apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: hello
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project contains CWA team application
  sourceRepos:
    - {GIT_REPOSITORY}
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
